version: "3"
services:
  react:
    restart: always
    build: ./client
    ports:
      - 3000:80

  node:
    restart: always
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./:/code

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - ./data:/data/import
volumes:
  mongodb:
